<!--头部-->
<div class="jm-header jm-header-column-two-right @@header-fixed">
    <div class="jm-wrapper">
         <div class="header-left-box">
               <i class="@@header-left-style"></i>
          </div>
        <div class="header-center-box @@header-mid-style">
         <p class="title">@@title</p>
         <div class="search-box">
            <form action="#" method="" class="search-form">
               <div class="inner-box">
                <input type="search" name="search-form-content" placeholder="输入搜索内容" class="search-form-item">
                <button type="submit" class="search-sub-btn"><i class="icon_header_shop_search"></i></button>
                <i class="icon_header_shop_search_cancel"></i>
               </div>
            </form>
         </div>
        </div>
           <div class="header-right-box">
           <span class="jm-header-login">登录</span>
           </div>
    </div>
</div>
<!--如果布局fixed，将占据垂直空间1.26rem-->
<div class="hold-space-top"></div>
<!--导航栏-->
<div class="header-nav-bar">
        <span class="triangle"></span>
        <ul>
            <a href="#"><li class="navltem bdr-bottom"><i class="navicon  icon_header_nav_home"></i>首页</li></a>
        </ul>
    </div>
