<!--尾部导航-->
<div id="footer" class="page-footer">
    <div class="footer_inner">
        <a class="on" href="#">
            <span class="line"><i class="icon-home"></i></span>
            <span class="text">首页</span>
        </a>
        <a href="#">
            <span class="line"><i class="icon-reorder"></i></span>
            <span class="text">分类</span></a>
        <a href="#">
            <span class="line"><i class="icon-shopping-cart"></i></span>
            <span class="text">购物车</span></a>
        <a href="#">
            <span class="line"><i class="icon-user"></i></span>
            <span class="text">个人中心</span>
        </a>
    </div>
</div>