<!--头部-->
<div class="jm-header header-fixed">
    <div class="jm-wrapper">
        <a href="javascript:history.go(-1);">
            <div class="posl icon icon_back icon-fix"></div>
        </a>
        <p class="title">@@title</p>
        <a href="#">
            <div class=" posr icon icon_header-nav-short"></div>
        </a>
    </div>

    <div class="nav">
        <span class="triangle"></span>
        <ul>
            <li class="navltem bdr-bottom"><i class="navicon  icon_header_nav_home"></i>首页</li>
            <li class="navltem bdr-bottom"><i class="navicon  icon_header_nav_home"></i>分类</li>
            <li class="navltem bdr-bottom"><i class="navicon  icon_header_nav_home"></i>首页</li>
            <li class="navltem bdr-bottom"><i class="navicon  icon_header_nav_home"></i>首页</li>
            <li class="navltem"><i class="navicon  icon_header_nav_home"></i>首页</li>
        </ul>
    </div>
</div>

<div class="hold-space-top"></div>