<!--头部-->
<div class="jm-header @@header-fixed">
    <div class="jm-wrapper">
        <a href="javascript:history.go(-1);">
            <div class="posl icon icon_back icon-fix"></div>
        </a>
        <p class="title">@@title</p>
        <a href="#">
            <div class=" posr icon icon_header-nav-short"></div>
        </a>
    </div>
</div>
<!--如果布局fixed，将占据垂直空间1.26rem-->
<div class="hold-space-top"></div>
<!--导航栏-->
<div class="header-nav-bar">
        <span class="triangle"></span>
        <ul>
            <a href="http://www.baidu.com"><li class="navltem bdr-bottom"><i class="navicon  icon_header_nav_home"></i>首页</li></a>
        </ul>
    </div>
