<!--banner 结构 swiper 框架-->
 <div class="banner mrg-bottom24">
    <div class="swiper-container">
        <div class="swiper-wrapper">
            <a
                    class="swiper-slide swiper-slide-active" href="javascript:void(0);"><img
                    src="../../assets/images/app/bbs/banner.png"></a>
            <a
                    class="swiper-slide swiper-slide-active" href="javascript:void(0);"><img
                    src="../../assets/images/app/bbs/banner2.png"></a>
        </div>
        <div class="swiper-pagination"></div>
    </div>
</div>




<!--
<script type="text/javascript">
  $(document).ready(function () {
    var mySwiper = new Swiper('.swiper-container', {
      direction: 'horizontal',
      loop: true,
      // 如果需要分页器
      pagination: '.swiper-pagination',
    })
  })
</script>
-->