/**底部导航**/
/**
.page-footer {
  height: 0.9rem;
  display: block;
  overflow: hidden;
  position: relative;

  .footer_inner {
    max-width: 1080px;
    width: 100%;
    background: #ffffff;
    bottom: 0;
    height: 0.9rem;
    position: fixed;
    z-index: 9990;
    border-top: 1px solid #e1e1e1;
    a {
      color: #3e3a39;
      display: block;
      float: left;
      font-size: 0.25rem;
      height: 0.9rem;
      text-align: center;
      width: 25%;
      &.on {
        color: #f23031;
    }
  }
    .line, .text {
      display: block;
      height: 0.4rem;
      line-height: 0.4rem;
  }
    .line {
      padding-top: 0.07rem;
      i {
        font-size: 0.38rem;
        width: 0.4rem;
        height: 0.4rem;
    }
  }
    .text {
      padding-bottom: 0.03rem;
  }
}
}
**/