<!--新尾部导航2017-6-23 transparent-bg  scroll-->
<div id="footer" class="new-app-page-footer">
    <ul class="footer_inner ">
        <li class="footer_item home">
            <a class="" href="./home.html">
            <i class="common_icon_fix icon-newfooter-home"></i>
             <span class="text">首页</span>
            </a>
        </li>
        <li class="footer_item bbs">
            <a class="on" href="./bbs.html">
                <i class="common_icon_fix icon-newfooter-bbs"></i>
                <span class="text">商圈</span>
            </a>
        </li>
        <li class="footer_item my">
            <a class="" href="./my-new.html">
                <i class="common_icon_fix icon-newfooter-my"></i>
                <span class="text">我的九件</span>
            </a>
        </li>
    </ul>
</div>