<!--新版尾部导航2017-6-23-->
<!--<div id="footer" class=" new-app-page-footer">
    <ul class="footer_inner">
        <li class="footer_item">
            <a class="on home" href="#">
               <i class="icon-newfooter-home"></i>
                <span class="text">首页</span>
            </a>
        </li>
        <li class="footer_item">
            <a class="bbs" href="#">
                <i class="icon-newfooter-bbs"></i>
                <span class="text">社区</span>
            </a>
        </li>
        <li class="footer_item">
            <a class="my" href="#">
                <i class="icon-newfooter-my"></i>
                <span class="text">我的九件</span>
            </a>
        </li>
    </ul>
</div>-->

<!--新版尾部导航2017-6-23  目前这种结构-->
<div id="footer" class=" new-app-page-footer">
    <ul class="footer_inner ">
        <li class="footer_item home">
            <a class="" href="#">
               <i class="icon-newfooter-home"></i>
                <span class="text">首页</span>
            </a>
        </li>
        <li class="footer_item bbs">
            <a class="" href="#">
                <i class="icon-newfooter-bbs"></i>
                <span class="text">社区</span>
            </a>
        </li>
        <li class="footer_item my">
            <a class="" href="#">
                <i class="icon-newfooter-my"></i>
                <span class="text">我的九件</span>
            </a>
        </li>
    </ul>
</div>