<!--老版本尾部导航-->
<div id="footer" class="app-page-footer">
    <div class="footer_inner bdr-top">
        <a class="on" href="./newtwitter.html">
            <span class="line"><i class="icon icon-invite"></i></span>
            <span class="text">邀请</span>
        </a>
        <a href="./myteam.html">
            <span class="line"><i class="icon icon-team"></i></span>
            <span class="text">团队</span></a>
        <a href="./myalliance.html">
            <span class="line"><i class="icon icon-alliance"></i></span>
            <span class="text">联盟</span></a>
        <a href="./my.html">
            <span class="line"><i class="icon icon-my"></i></span>
            <span class="text">我的</span>
        </a>
    </div>
</div>