<div id="footer" class="new-store-page-footer">
    <ul class="footer_inner ">
        <li class="footer_item">
            <a class="on  link" href="#">
            <span class="icon-box">
                <i class="store_common_icon_fix icon_shop_index"></i>
            </span>

             <span class="text">返回九件</span>
            </a>
        </li>
        <li class="footer_item">
            <a class="link" href="#">
                <span class="icon-box">
                    <i class="store_common_icon_fix icon_store_index"></i>
                </span>

                <span class="text">店铺</span>
            </a>
        </li>
        <li class="footer_item">
            <a class="link" href="#">
                <span class="icon-box">
                    <i class="store_common_icon_fix icon_store_car"></i>
                </span>
                <span class="text">购物车</span>
            </a>
        </li>
        <li class="footer_item">
            <a class="link" href="#">
                <span class="icon-box">
                    <i class="store_common_icon_fix icon_store_my"></i>
                </span>
                <span class="text">我的</span>
             </a>
        </li>
    </ul>
</div>