   <meta charset="utf-8">
    <meta name="viewport" content="width=device-width,initial-scale=1, maximum-scale=1, minimum-scale=1, user-scalable=no" />
    <meta content="telephone=no" name="format-detection" />
    <meta name="google" value="notranslate" />
    <meta name="root-url" value="<?php echo JQ_URL; ?>" />
    <meta http-equiv="Cache-Control" content="no-cache, no-store, must-revalidate" />
    <meta http-equiv="Pragma" content="no-cache" />
    <meta http-equiv="Expires" content="0" />
    <meta http-equiv="x-dns-prefetch-control" content="on" />
    <title>@@title</title>
    <link rel="stylesheet" href="../../styles/swiper.min.css" />
    <link rel="stylesheet" href="../../styles/framework.css" />
    <link rel="stylesheet" href="../../styles/app-base.css" />
    <link rel="stylesheet" href="../../styles/ricky.css?v=04062" />
   <script type="text/javascript" src="../../scripts/zepto.min.js"></script>
    <script type="text/javascript" src="../../scripts/zepto.swiper.min.js"></script>
   <!--<script type="text/javascript" src="../../scripts/zepto.app.js?v=04063"></script>
    <script type="text/javascript" src="../../scripts/zepto.custom.js?v=04062"></script>-->
